Build the Documentation. (#17)
* Corrections of docstrings and some clean up.

* Add Differential import to main __init__.py

To solve this issue when building docs.

AttributeError: module 'spectrum_overload' has no attribute 'Differential'

* Update doc strings in classes.

* Add paths to module in doc conf.

* Change default theme.

* Update index.rst

* Add documentation about installation.

* Quickstart doc.

* Document available classes.

Using autodoc.

* Tidy spacing in docs.

* rearrange order of requirements.

* Add numpy to setup_requires.

To resolve issue with pyastronomy.

* Remove pyastronomy from requirements.txt

* Update requirements regarding pyastronomy.

* Edits to quickstart.

* Add docs extra_requirements to setup.py

* Run requirements.txt in setup.py.

* Add pyastronomy to travis.yml

So that tests will run before pyastronomy fixed.

* Adjust comment of setup.cfg - unimportant

* Fix setup.py error.

missing comma for docs: dependencies.

* Try empty install requires.

* Add readthedocs YAML config file.

* try pyastronomy in doc requirements.

* Add docs/.build to gitignore.

Ignores build files for docs.

* Add editable installation to docs.

* Note about classes not building.

And how to build manually.

* Re-add index and search to home page.